CREATE TABLE `basestrings` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SITEID` int(10) unsigned NOT NULL,
  `PAGEID` bigint(20) unsigned DEFAULT NULL,
  `TEXT` text,
  `TYPE` smallint(6) DEFAULT '0',
  PRIMARY KEY (`ID`,`SITEID`),
  KEY `PAGESTRINGS_idx` (`PAGEID`),
  CONSTRAINT `PAGESTRINGS` FOREIGN KEY (`PAGEID`) REFERENCES `pagestrings` (`PAGEID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `pages` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `PAGE` varchar(256) DEFAULT NULL,
  `SITEID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SITE_ID` (`SITEID`),
  KEY `PAGE` (`SITEID`,`PAGE`(255)),
  CONSTRAINT `SITE_ID` FOREIGN KEY (`SITEID`) REFERENCES `sites` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pagestrings` (
  `PAGEID` bigint(20) unsigned NOT NULL,
  `STRINGID` bigint(20) NOT NULL,
  PRIMARY KEY (`PAGEID`,`STRINGID`),
  KEY `PAGE` (`PAGEID`),
  CONSTRAINT `PAGE` FOREIGN KEY (`PAGEID`) REFERENCES `pages` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sitelocales` (
  `SITEID` int(10) unsigned NOT NULL,
  `LOCALE` char(8) NOT NULL,
  PRIMARY KEY (`SITEID`,`LOCALE`),
  KEY `FK_SITE` (`SITEID`),
  CONSTRAINT `SITE` FOREIGN KEY (`SITEID`) REFERENCES `sites` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `sites` (
  `HOST` char(75) NOT NULL,
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ANCHOR` char(1) NOT NULL,
  `BASELOCALE` char(8) NOT NULL,
  `OFFSET` int(11) NOT NULL,
  `TOP` int(11) NOT NULL,
  `TRANSLATIONVERSION` int(11) DEFAULT '0',
  PRIMARY KEY (`ID`,`HOST`),
  UNIQUE KEY `DOMAIN_UNIQUE` (`HOST`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `siteusers` (
  `SITEID` int(11) unsigned NOT NULL,
  `USERID` int(11) unsigned NOT NULL,
  `ROLE` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`SITEID`,`USERID`),
  KEY `FK_SITEUSERS` (`SITEID`),
  KEY `FK_SITEUSER` (`USERID`),
  CONSTRAINT `SITES` FOREIGN KEY (`SITEID`) REFERENCES `sites` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `targetstrings` (
  `LOCALE` char(8) NOT NULL,
  `BASEID` bigint(20) unsigned NOT NULL,
  `TEXT` text,
  PRIMARY KEY (`LOCALE`,`BASEID`),
  KEY `BASESTRING` (`BASEID`),
  CONSTRAINT `BASESTRING` FOREIGN KEY (`BASEID`) REFERENCES `basestrings` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERID` varchar(45) NOT NULL,
  `MAIL` varchar(255) NOT NULL DEFAULT '',
  `NAME` varchar(255) DEFAULT NULL,
  `SURNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` char(60) DEFAULT NULL,
  `ACTIVE` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER` (`USERID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `validationkeys` (
  `USERID` int(11) NOT NULL,
  `VALIDATIONKEY` char(36) NOT NULL,
  `DATECREATED` datetime DEFAULT NULL,
  PRIMARY KEY (`USERID`),
  CONSTRAINT `FK_USER` FOREIGN KEY (`USERID`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
